services:

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  billing-ingestion-service:
    build:
      context: .
      dockerfile: Dockerfile.billing
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    
volumes:
  my-db:
