services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  billing-ingestion-service:
    build:
      context: .
      dockerfile: Dockerfile.billing
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_NAME: db
      NODE_ENV: production
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  my-db:
