version: '3.4'

services:
  imurmurhash:
    image: imurmurhash
    build:
      context: node_modules/imurmurhash
      dockerfile: ./Dockerfile.billing
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "imurmurhash.js"]
