version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14.17.0

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Images
          command: docker-compose build

      - run:
          name: Push Docker Images to Registry
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker tag project_billing-ingestion-service:latest $DOCKERHUB_USER/tecsus_backend-billing-ingestion-service
            docker push $DOCKERHUB_USER/tecsus_backend-billing-ingestion-service
            docker tag project_mysql:latest $DOCKERHUB_USER/tecsus_backend-mysql
            docker push $DOCKERHUB_USER/tecsus_backend-mysql

      - run:
          name: Deploy to Railway
          command: |
            railway up

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
