version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14.17.0

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Images
          command: docker-compose build

      - run:
          name: Push Docker Images to Registry
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker tag project_billing-ingestion-service:latest $DOCKERHUB_USER/tecsus_backend-billing-ingestion-service
            docker push $DOCKERHUB_USER/tecsus_backend-billing-ingestion-service
            docker tag project_mysql:latest $DOCKERHUB_USER/tecsus_backend-mysql
            docker push $DOCKERHUB_USER/tecsus_backend-mysql

      - run:
          name: Update CA Certificates
          command: |
            sudo apt-get update
            sudo apt-get install -y ca-certificates

      - run:
          name: Install Railway CLI
          command: |
            curl -sSL https://railway.app/install.sh | sh
            echo 'export PATH="$HOME/.railway/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Authenticate Railway
          command: |
            echo $RAILWAY_TOKEN | railway login

      - run:
          name: Deploy to Railway
          command: |
            railway up --project-id $RAILWAY_PROJECT_ID --service-all --env prod --detach

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
