name: NestJS CI/CD

on:
  push:
    branches:
      - main  # Adjust this to your main branch name
  pull_request:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  setup_and_install_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Install NestJS CLI
      run: yarn add --dev @nestjs/cli
    
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-

    - name: Setup complete
      id: setup_complete
      run: echo "Setup is complete, ready to proceed"

  build:
    needs: setup_and_install_dependencies
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Restore cached dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: yarn build

    - name: Cache build artifacts
      uses: actions/cache@v2
      with:
        path: ./dist
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-nest-build-${{ hashFiles('**/dist/**') }}

  test:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Restore cached dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Restore cached build artifacts
      uses: actions/cache@v2
      with:
        path: ./dist
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-nest-build-${{ hashFiles('**/dist/**') }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Test
      run: yarn test
