name: NestJS CI/CD

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code and set up Node.js
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build the project
        run: yarn build

      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: ./dist
          key: ${{ runner.os }}-node-20-nest-build-${{ hashFiles('**/dist/**') }}

      - name: Test the build
        run: yarn test
