name: NestJS CI/CD

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  setup_and_install_dependencies:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-keys.outputs.cache-key }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js and cache Yarn dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache key for dependencies
        id: cache-keys
        run: echo "::set-output name=cache-key::${{ runner.os }}-node-20-yarn-${{ hashFiles('**/yarn.lock') }}"

      - name: Setup complete
        run: echo "Setup is complete, ready to proceed"

  build:
    needs: setup_and_install_dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (Caching handled in previous job)
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Build the project
        run: yarn build

      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: ./dist
          key: ${{ runner.os }}-node-20-nest-build-${{ hashFiles('**/dist/**') }}

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Restore cached build artifacts
        uses: actions/cache@v2
        with:
          path: ./dist
          key: ${{ runner.os }}-node-20-nest-build-${{ hashFiles('**/dist/**') }}

      - name: Test the build
        run: yarn test
